### PR TITLE
Add monaco-editor dependency to readme

### PR DESCRIPTION
**Pull request by Ehesp**
Since it's required for this package to work..

Fixes https://github.com/react-monaco-editor/react-monaco-editor/issues/272

### CODE REVIEW

**Comment by domoritz** [comment]
Maybe we should just make it a dependency in package.json then.

**Comment by Ehesp** [comment]
Your call; leaving it out would give users more control of what version they want to sync with.

**Comment by domoritz** [comment]
I think I'll just add it since I keep this repo updated regularly.

**Comment by domoritz** [comment]
Fixed in 496c0a8

**Pull request closed without merging**
