### PR TITLE
Update to monaco-editor 0.17.1

### PR DESCRIPTION
**Pull request by cronco**
0.17.1 updated monaco-typescript to 3.5.0.

Also create a package-lock.json file and updated some security vulnerabilities brought up by npm audit.

### CODE REVIEW

**Comment by domoritz** [comment]
We use yarn lockfiles instead of package.lock files. Can you undo that change and update with yarn instead?

**Comment by cronco** [comment]
> We use yarn lockfiles instead of package.lock files. Can you undo that change and update with yarn instead?

Sure thing

**Comment by domoritz** [comment]
Please make sure that the example still works. You can update its dependencies as well.

**Comment by cronco** [comment]
> Please make sure that the example still works. You can update its dependencies as well.

The example seems to work fine, I just checked it right now.

I've also noticed the `yarn` command updated the versions of a lot of packages in yarn.lock, which was not intended, but doesn't seem to break anything either.

**Comment by domoritz** [comment]
Feel free to try to delete the yarn.lock file and create a new one with the latest versions. I think keeping dependencies up to date is good.

**Comment by cronco** [comment]
That's what I did, I deleted the yarn.lock to make sure the latest version of `monaco-editor` is fetched.

If updating all those packages is not a dealbreaker, then I am waiting any other suggestions you might have on the PR.

**Comment by domoritz** [comment]
Feel free to update all dependencies that can be updated. I usually use https://www.npmjs.com/package/npm-check-updates.

**Comment by cronco** [comment]
Minor versions only? Do you still want to support react 15 for example?

**Comment by domoritz** [comment]
Yes, let's leave react 15 support. No, also major versions.

**Comment by cronco** [comment]
This spiraled out of control once I upgraded to the latest babel and the example stopped working because `json` doesn't get appended to `monaco.languages` anymore. 

I feel a bit out of my depth, it would help if I'd get some guidance.

**Comment by domoritz** [comment]
Thanks for looking into this. Let's start with only updating Monaco then and merging that, okay?

**Comment by cronco** [comment]
The pull request as is updates monaco-editor only, I believe it is ready for merge.

**Pull request merged**
